version: '3'

services:
  users:
    image: users-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: file:../../storage/service.db
      NODE_ENV: production
      PORT: 80
    volumes:
      - ./storage:/app/storage
    ports:
      - ${PORT:-3000}:80
