version: '3'

services:
  users:
    image: users-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: file:./service.db
      NODE_ENV: production
      PORT: 80
    volumes:
      - ./prisma:/app/prisma
    ports:
      - 3000:80
